services:
  postgres:
    image: postgres:17
    container_name: postgres

    environment:
      POSTGRES_DB: shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shortener"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  shorter-service:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: shorter-service

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/shortener
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      BASE_URL: http://localhost:8080/

    ports:
      - "8080:8080"

volumes:
  postgres-data: